Pull request for code review
visva-dev/Building-with-Responsive-Design pull request #3
Opened 2020-06-05 12:19 UTC by visva-dev

2020-06-05 17:56 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-06-05 17:56 UTC, addod19 requested changes
## Status: Require changes:recycle: :traffic_light: 

Hi, @visva-dev and @ahmadchata, great job with this project :+1: PR looks professional, nice commit messages except that they are written in the past tense. Great use of the Mobile-first design approach. :smile: Great use of HTML semantics. Let us improve our project and get our project approved by working on the comments below: :slightly_smiling_face: 
- The larger image of the 3 articles should take 2/3 if the width
![bigger](https://user-images.githubusercontent.com/46388113/83906419-12566f00-a753-11ea-8955-d035edaf2644.png)
```Clone```
![mmain1](https://user-images.githubusercontent.com/46388113/83906452-200bf480-a753-11ea-8222-5e1272536dc7.png)
```Source```
![mmain](https://user-images.githubusercontent.com/46388113/83906479-2c904d00-a753-11ea-8b68-38f3840d1af7.png)
- Let us add a detailed description to the README file
- Let us use CSS float property for aligning elements for this project. Currently, we are missing this property
![imp](https://user-images.githubusercontent.com/46388113/83907734-72e6ab80-a755-11ea-80a0-854fb0031913.png)

Kindly implement these changes and submit another code review :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-06-06 13:24 UTC, ahmadchata commented
## Changes Made

- The larger image in the article section now takes 2/3 of the width.
- A detailed description of the project is added to the README file.
- The screenshot in the README file is updated to the latest version.

2020-06-06 13:50 UTC, BrittanyBlake commented
### Pull Request under review by Brittany Blake (TSE)

2020-06-06 14:13 UTC, BrittanyBlake commented on styles.css
> +      'news news news3';
Please use this  [article](https://developer.mozilla.org/es/docs/Web/CSS/grid-template-areas)  to determine the proper way to set the grid

2020-06-06 14:18 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi @ahmadchata and @visva-dev! 👋 👋 
Great job implementing the changes requested by the previous TSE! 🎖️ You have done a wonderful job so far! 👍 However, there is still one issue that needs to be addressed before you can move on 🔽
****

- [ ] As requested by the previous TSE, the larger image of the 3 articles should take 2/3 if the width. Your clone still does not satisfy this requirement:
Original Page 👇 
![Screen Shot 2020-06-06 at 4 03 22 PM](https://user-images.githubusercontent.com/48804258/83946276-0da3c080-a810-11ea-9bd0-c767cef8f1a4.png)
Your clone 👇 
![Screen Shot 2020-06-06 at 4 03 34 PM](https://user-images.githubusercontent.com/48804258/83946279-0f6d8400-a810-11ea-9f2f-0e466ee6d951.png)

You can find more information about how to use `grid-template-area` [here](https://developer.mozilla.org/es/docs/Web/CSS/grid-template-areas)
****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-06-06 14:54 UTC, ahmadchata commented
## Changes Made

- The larger image in the article section now takes 2/3 of the width for 768px

2020-06-06 15:05 UTC, BrittanyBlake approved these changes
### Status: Approved ✅ 
****
### Hi Team! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****

_P.S. Make sure to update the live demo link in your README file_ 😄 

 Good Luck and Happy Coding! 🍀 👩🏾‍💻

2020-06-06 15:26 UTC, merged